name: Docker Image CI

on:
  push:
    branches: [ master ]

env:
  VERSION: ${{ github.sha }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login into registry
      run:  docker login docker.pkg.github.com --username skhalife --password ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Build the Docker image for web/
      run: |
        cd web/
        docker build . --file Dockerfile --tag docker.pkg.github.com/skhalife/k8s-wordsmith/web:${VERSION}
        docker push docker.pkg.github.com/skhalife/k8s-wordsmith/web:${VERSION}
    - name: Build the Docker image for words/
      run: |
        cd words/
        docker build . --file Dockerfile --tag docker.pkg.github.com/skhalife/k8s-wordsmith/words:${VERSION}
        docker push docker.pkg.github.com/skhalife/k8s-wordsmith/words:${VERSION}
    - name: Build the Docker image for db/
      run: |
        cd db/
        docker build . --file Dockerfile --tag docker.pkg.github.com/skhalife/k8s-wordsmith/db:${VERSION}
        docker push docker.pkg.github.com/skhalife/k8s-wordsmith/db:${VERSION}

