name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
    - run: |
        VERSION=$(date +%s)
        docker login docker.pkg.github.com --username skhalife --password ${{ secrets.GITHUB_TOKEN }}
    - run: |
        cd web/
        docker build . --file Dockerfile --tag docker.pkg.github.com/skhalife/k8s-wordsmith/web:${VERSION}
        docker push docker.pkg.github.com/skhalife/k8s-wordsmith/web:${VERSION}
    - run: |
        cd ../words
        docker build . --file Dockerfile --tag docker.pkg.github.com/skhalife/k8s-wordsmith/words:${VERSION}
        docker push docker.pkg.github.com/skhalife/k8s-wordsmith/words:${VERSION}
    - run: |
        cd ../db
        docker build . --file Dockerfile --tag docker.pkg.github.com/skhalife/k8s-wordsmith/db:${VERSION}
        docker push docker.pkg.github.com/skhalife/k8s-wordsmith/db:${VERSION}

